namespace UFCaseImageHost
{
    [default_interface]
    runtimeclass Class
    {
        Class();
        Int32 MyProperty;

        Windows.Foundation.Collections.IVector<UFCase.ImageViewModel> GetImages();
    }
}
