namespace UFCase
{
    [default_interface]
    runtimeclass AddSourceContentDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        AddSourceContentDialog();

        String SourcePath{ get; };
    }
}
