import "ManifestAssemblyViewModel.idl";

namespace UFCase
{
    [bindable]
    [default_interface]
    runtimeclass AssemblyManifestViewerWindowViewModel 
    {
        AssemblyManifestViewerWindowViewModel(UFCase.Isolation.ComponentModel model);

        ManifestAssemblyViewModel Assembly{ get; };
    }
}
