import "ImageViewModel.idl";
import "ComponentViewModel.idl";

import "RelayCommand.idl";

import "Identity.idl";

namespace UFCase
{
    enum ComponentsPageNavigationContextType
    {
        None,
        SelectCompId,
        SelectCompIdentity,
    };

    runtimeclass ComponentsPageNavigationContext
    {
        ComponentsPageNavigationContext();
        static ComponentsPageNavigationContext GetFromId(String select_comp_id);
        static ComponentsPageNavigationContext GetFromIdentity(Identity select_comp_identity);

        ComponentsPageNavigationContextType Type;

        String SelectCompId;

        Identity SelectCompIdentity;
    }

    enum ComponentsPageViewModelState
    {
        Uninitialized,
        Idle,
        Loading,
    };

    [default_interface]
    runtimeclass ComponentsPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ComponentsPageViewModel(ImageViewModel image);

        ComponentsPageViewModelState State{ get; };

        Windows.Foundation.IAsyncActionWithProgress<UInt32> PullData();

        Windows.Foundation.Collections.IObservableVector<ComponentViewModel> Components{ get; };

        ComponentViewModel SelectedComponent;

        RelayCommand ComponentShowManifestRelay{ get; };
        RelayCommand ComponentShowInFileExplorerRelay{ get; };

        ComponentsPageNavigationContext NavContext;
    }
}
