namespace UFCase
{
    struct ComponentFileViewModel
    {
        String Name;
        String Status;
    };

    [default_interface]
    runtimeclass ComponentViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ComponentViewModel(UFCase.Isolation.ComponentModel model);

        UFCase.Isolation.ComponentModel Model{ get; };

        String TextForm{ get; };
        String KeyForm{ get; };

        String Name{ get; };
        String Culture{ get; };
        String Version{ get; };
        String PublicKeyToken{ get; };
        String ProcessorArchitecture{ get; };
        String VersionScope{ get; };

        String Manifest{ get; };

        String Status{ get; };
        String PayloadPath{ get; };

        Windows.Foundation.Collections.IObservableVector<ComponentFileViewModel> Files{ get; };
    }
}
