import "ComponentsPageViewModel.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass ComponentsPage : Microsoft.UI.Xaml.Controls.Page
    {
        ComponentsPage();

        ComponentsPageViewModel ViewModel{ get; };
    }
}
