namespace UFCase
{

    [default_interface]
    runtimeclass HrError
    {
        HrError();
        HrError(UInt32 hr);

        UInt32 Code;
        String Message;
    }

    [default_interface]
    runtimeclass ErrorDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        ErrorDialog(HrError error);
        
        Microsoft.UI.Xaml.Controls.TextBlock TitleBlock;
        Microsoft.UI.Xaml.Controls.TextBlock MsgBlock;
    }
}
