import "FeatureViewModel.idl";
import "FeaturesPageViewModel.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass FeaturesPage : Microsoft.UI.Xaml.Controls.Page
    {
        FeaturesPage();

        FeaturesPageViewModel ViewModel{ get; };
        
        Microsoft.UI.Xaml.Controls.TreeView FeatureTree;

        Microsoft.UI.Xaml.Visibility ConvertUInt32ToVisibility(UInt32 value);

        Microsoft.UI.Xaml.Input.XamlUICommand FeatureEnableCommand;
        Microsoft.UI.Xaml.Input.XamlUICommand FeatureDisableCommand;
        Microsoft.UI.Xaml.Input.XamlUICommand FeatureGobackCommand;
        Microsoft.UI.Xaml.Input.XamlUICommand FeatureOpenExplorerCommand;
        Microsoft.UI.Xaml.Input.XamlUICommand FeatureOpenRegistryCommand;
    }
}
