import "ImageViewModel.idl";
import "FeatureViewModel.idl";

import "RelayCommand.idl";

namespace UFCase
{

    enum FeaturesPageViewModelState
    {
        Uninitialized,
        Idle,
        Loading,
    };

    [bindable]
    [default_interface]
    runtimeclass FeaturesPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        FeaturesPageViewModel(ImageViewModel image);

        FeaturesPageViewModelState State{ get; };

        ImageViewModel Image{ get; };
        Windows.Foundation.Collections.IObservableVector<FeatureViewModel> RootFeatures{ get; };

        FeatureViewModel SelectedFeature;

        Windows.Foundation.IAsyncActionWithProgress<UInt32> PullData();

        RelayCommand FeatureEnableRelay{ get; };
        RelayCommand FeatureDisableRelay{ get; };
        RelayCommand FeatureGotoPackageRelay{ get; };

        RelayCommand FeatureSystemRelay{ get; };
        RelayCommand FeatureAddSourceRelay{ get; };

        RelayCommand CommitRelay{ get; };
        RelayCommand RefreshRelay{ get; };
    }
}
