import "ImageViewModel.idl";
import "FeatureViewModel.idl";

namespace UFCase
{
    [bindable]
    [default_interface]
    runtimeclass FeaturesPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        FeaturesPageViewModel(ImageViewModel image);

        ImageViewModel Image{ get; };
        Windows.Foundation.Collections.IObservableVector<FeatureViewModel> RootFeatures{ get; };

        Windows.Foundation.IAsyncActionWithProgress<UInt32> PullData();


    }
}
