import "FeatureTreeElement.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass FeaturesPage : Microsoft.UI.Xaml.Controls.Page
    {
        FeaturesPage();

        Windows.Foundation.Collections.IObservableVector<FeatureTreeElement> FeatureDataSource{ get; };
        Microsoft.UI.Xaml.Controls.TreeView FeatureTree;

        // binding helper functions
        Boolean IsFeatureStateCheckBoxEnabled(FeatureState state);
        Windows.Foundation.IReference<Boolean> IsFeatureStateCheckBoxCheckd(FeatureState state);
    }
}
