import "ImageProvider.idl";
import "PackageViewModel.idl";

namespace UFCase
{
    enum FeatureState
    {
        Invalid,
        Unavailable,
        Disabled,
        PartiallyEnabled,
        Enabled,
    };

    [bindable]
    [default_interface]
    runtimeclass FeatureViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        FeatureViewModel(UInt64 hModel);
        
        String Name{ get; };
        String Description{ get; };
        String Identity{ get; };
        FeatureState State{ get; };
        String StateText{ get; };

        String DisplayFile{ get; };
        String Restart{ get; };
        String PsfName{ get; };
        String DownloadSize{ get; };
        String SetMembership{ get; };

        PackageViewModel Package{ get; };

        Windows.Foundation.Collections.IObservableVector<FeatureViewModel> Children{ get; };

        Boolean IsEnabled{ get; };
        Windows.Foundation.IReference<Boolean> IsChecked{ get; };

        String ModificationMark{ get; set; };
        Microsoft.UI.Xaml.Controls.IconSource Icon{ get; };

        void Enable();
        void Disable();

    }
}
