import "FeatureViewModel.idl";
import "FeaturesPageViewModel.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass FeaturesPage : Microsoft.UI.Xaml.Controls.Page
    {
        FeaturesPage();

        FeaturesPageViewModel ViewModel{ get; };
        
        Microsoft.UI.Xaml.Controls.TreeView FeatureTree;
    }
}
