namespace UFCase.Isolation
{
    runtimeclass HostManager : [default] IHostManager
    {
    }

    runtimeclass HostManagerStatics : [default] IHostManagerStatics
    {
        HostManagerStatics
    }
}
