namespace UFCase
{
    enum IdentityType
    {
        Component,
        Package,
    };

    [bindable]
    [default_interface]
    runtimeclass Identity 
    {
        Identity();

        // Name~PublicKeyToken~Architecture~Culture~Version
        // Containers-ApplicationGuard-Package~31bf3856ad364e35~amd64~~10.0.22621.2792
        static Identity ParsePackageFromTildeForm(String tilde_form);

        IdentityType Type;

        String ImageRoot;

        String Name;
        String Version;
        String Culture;
        String PublicKeyToken;
        String ProcessorArchitecture;
        String VersionScope;

        UInt64 GetHashCode();

        String GetDisplayForm();
        String GetKeyForm();
        String GetTildeForm();

        static Boolean RoughMatch(Identity a, Identity b);
    }
}
