namespace UFCase
{

    [default_interface]
    runtimeclass ImageItem
    {
        ImageItem();
        ImageItem(String type, String ver, String bootdrv, Microsoft.UI.Xaml.Media.ImageSource icon);

        String Type;
        String Version;
        String Bootdrive;
        Microsoft.UI.Xaml.Media.ImageSource Icon;

    }

    [bindable]
    [default_interface]
    runtimeclass ImageProvider : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ImageProvider();
        Windows.Foundation.Collections.IObservableVector<ImageItem> Images{ get; };
        Int32 SelectedIndex;
    }
}
