
namespace UFCase
{
    [bindable]
    [default_interface]
    runtimeclass ImageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ImageViewModel(UInt64 hModel);

        String Type{ get; };
        String Version{ get; };
        String Edition{ get; };
        String Bootdrive{ get; };

        Boolean Selectable{ get; };

        Microsoft.UI.Xaml.Media.ImageSource Icon{ get; };

        void Select();

        UInt64 OpenSession();
        void CloseSession(UInt64 hModel);
    }
}
