
namespace UFCase
{
    [bindable]
    [default_interface]
    runtimeclass ImageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ImageViewModel(UFCase.Isolation.ImageModel model);

        String Type{ get; };
        String Version{ get; };
        String Edition{ get; };
        String Bootdrive{ get; };

        Boolean Selectable{ get; };

        Microsoft.UI.Xaml.Media.ImageSource Icon{ get; };

        UFCase.Isolation.SessionModel OpenSession();

        UFCase.Isolation.ImageModel Model{ get; };
        UFCase.Isolation.StoreModel Store{ get; };
    }
}
