import "ImageViewModel.idl";

namespace UFCase
{
    [bindable]
    [default_interface]
    runtimeclass ImageSelectorViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ImageSelectorViewModel();

        Windows.Foundation.Collections.IObservableVector<ImageViewModel> Images{ get; };
        Int32 SelectedIndex;
        ImageViewModel SelectedImageViewModel{ get; };
        UFCase.Isolation.ImageModel SelectedImageModel{ get; };

        Windows.Foundation.IAsyncActionWithProgress<String> PullData();
    }
}
