namespace UFCase
{

    [default_interface]
    runtimeclass MainProgressService : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainProgressService();
        UInt32 CurrentProgress{ get; };
        Microsoft.UI.Xaml.Visibility Visibility{ get; };
        
        Windows.Foundation.IAsyncAction InsertTask(Windows.Foundation.IAsyncActionWithProgress<UInt32> provider, UInt32 weight);
    }
}
