import "ImageSelectorViewModel.idl";
import "MainProgressService.idl";
import "MainNavigationService.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        
        // UI elements
        Microsoft.UI.Xaml.Controls.NavigationView NavView;
        ImageSelectorViewModel ImageSelectorVM;
        Microsoft.UI.Xaml.Controls.Frame ContentFrame;
        Microsoft.UI.Xaml.Controls.ComboBox ImageComboBox;

        // Services
        MainNavigationService NavigationService;
        MainProgressService ProgressService;
    }
}
