import "ImageProvider.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        
        // UI elements
        // Microsoft.UI.Xaml.Controls.NavigationView NavView;
        Microsoft.UI.Xaml.Controls.Frame ContentFrame;
        Microsoft.UI.Xaml.Controls.ComboBox ImageComboBox;

        // Modules
        ImageProvider ImageProv {get;};
    }
}
