import "ManifestViewerWindowViewModel.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass ManifestViewerWindow : Microsoft.UI.Xaml.Window
    {
        ManifestViewerWindow(ManifestViewerWindowViewModel view_model);

        ManifestViewerWindowViewModel ViewModel{ get; };
    }
}
