import "PackagesPageViewModel.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass PackagesPage : Microsoft.UI.Xaml.Controls.Page
    {
        PackagesPage();

        PackagesPageViewModel ViewModel{ get; };
        Microsoft.UI.Xaml.Controls.ListView PkgList{ get; };
    }
}
