import "ImageViewModel.idl";
import "PackageViewModel.idl";

namespace UFCase
{
    runtimeclass PackagesPageNavigationContext
    {
        PackagesPageNavigationContext();

        String SelectPkgId;
    }

    [bindable]
    [default_interface]
    runtimeclass PackagesPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PackagesPageViewModel(ImageViewModel image);
        PackagesPageViewModel(ImageViewModel image, PackagesPageNavigationContext ctx);

        ImageViewModel Image{ get; };
        Windows.Foundation.Collections.IObservableVector<PackageViewModel> Packages{ get; };
        PackageViewModel SelectedPackage;

        PackagesPageNavigationContext NavContext{ get; };

        Microsoft.UI.Xaml.Input.XamlUICommand PackageShowManifestCommand{ get; };
        Microsoft.UI.Xaml.Input.XamlUICommand PackageShowInFileExplorerCommand{ get; };
        Microsoft.UI.Xaml.Input.XamlUICommand PackageShowInRegistryCommand{ get; };

        Windows.Foundation.IAsyncActionWithProgress<UInt32> PullData();
        Windows.Foundation.IAsyncActionWithProgress<UInt32> PullData(Boolean is_navigation);
    }
}
