namespace UFCase
{
    enum PackageState
    {
        PartiallyInstalled = -5,
        Cancel = -4,
        Superseded = -3,
        Default = -2,
        Unknown = -1,
        Absent = 0,
        Resolving = 1,
        Resolved = 2,
        Staging = 3,
        Staged = 4,
        UninstallRequested = 5,
        InstallRequested = 6,
        Installed = 7,
        Permanent = 8,
    };

    [bindable]
    [default_interface]
    runtimeclass PackageViewModel
    {
        PackageViewModel(UFCase.Isolation.PackageModel model);

        String ListName { get; };
        String ListIdentity { get; };
        Microsoft.UI.Xaml.Visibility ListIdentityVisibility { get; };

        String DetailName{ get; };
        String DetailIdentity{ get; };

        String ReleaseType { get; };
        String State { get; };
        String Description { get; };
        String RestartRequired { get; };
        String ProductName { get; };
        String ProductVersion { get; };
        String Company { get; };
        String Copyright { get; };
        String SupportInformation { get; };
        String CreationTime { get; };
        String LastUpdateTime { get; };
        String InstallTime { get; };
        String InstallPackageName { get; };
        String InstallLocation { get; };
        String InstallClient { get; };
        String InstallUserName { get; };
        Boolean IsApplicable { get; };

        String ManifestFilePath { get; };
        String RegistryPath { get; };
    }
}
