import "ImageViewModel.idl";
import "PackageViewModel.idl";

import "RelayCommand.idl";

namespace UFCase
{
    runtimeclass PackagesPageNavigationContext
    {
        PackagesPageNavigationContext();

        String SelectPkgId;
    }

    enum PackagesPageViewModelState
    {
        Uninitialized,
        Idle,
        Loading,
    };

    [bindable]
    [default_interface]
    runtimeclass PackagesPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PackagesPageViewModel(ImageViewModel image);
        PackagesPageViewModel(ImageViewModel image, PackagesPageNavigationContext ctx);

        PackagesPageViewModelState State{ get; };

        ImageViewModel Image{ get; };
        Windows.Foundation.Collections.IObservableVector<PackageViewModel> Packages{ get; };
        PackageViewModel SelectedPackage;

        PackagesPageNavigationContext NavContext;

        RelayCommand PackageShowManifestRelay{ get; };
        RelayCommand PackageShowInFileExplorerRelay{ get; };
        RelayCommand PackageShowInRegistryRelay{ get; };

        Windows.Foundation.IAsyncActionWithProgress<UInt32> PullData();
        Windows.Foundation.IAsyncActionWithProgress<UInt32> PullData(Boolean is_navigation);
    }
}
