import "ImageViewModel.idl";
import "PackageViewModel.idl";

import "RelayCommand.idl";

namespace UFCase
{
    enum PackagesPageNavigationContextType
    {
        None,
        SelectPkgStringId,
        SelectPkgIdentity,
    };

    runtimeclass PackagesPageNavigationContext
    {
        PackagesPageNavigationContext();
        static PackagesPageNavigationContext GetFromId(String select_pkg_id);
        static PackagesPageNavigationContext GetFromIdentity(Identity select_pkg_identity);

        PackagesPageNavigationContextType Type;

        String SelectPkgStringId;

        Identity SelectPkgIdentity;
    }

    enum PackagesPageViewModelState
    {
        Uninitialized,
        Idle,
        Loading,
        Failed,
    };

    [bindable]
    [default_interface]
    runtimeclass PackagesPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PackagesPageViewModel(ImageViewModel image);

        PackagesPageViewModelState State{ get; };

        ImageViewModel Image{ get; };
        Windows.Foundation.Collections.IObservableVector<PackageListItem> Packages{ get; };
        PackageListItem SelectedPackage;
        PackageDetails SelectedPackageDetails{ get; };
        String SelectedPackageDetailName{ get; };
        String SelectedPackageDetailIdentity{ get; };
        String SelectedPackageDescription{ get; };
        String SelectedPackageInstallTime{ get; };
        String SelectedPackageInstallClient{ get; };

        RelayCommand PackageShowManifestRelay{ get; };
        RelayCommand PackageShowInFileExplorerRelay{ get; };
        RelayCommand PackageShowInRegistryRelay{ get; };

        void Navigate(PackagesPageNavigationContext context);
        event Windows.Foundation.TypedEventHandler<PackagesPageViewModel, PackagesPageNavigationContext> Navigated;
    }
}
