import "PackagesProvider.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass PackagesPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PackagesPage();

        PackagesProvider PackageDataSource{ get; };
        Microsoft.UI.Xaml.Controls.ListView PkgList{ get; };
    }
}
