import "SysInfoElement.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass SysInfoPage : Microsoft.UI.Xaml.Controls.Page
    {
        SysInfoPage();
        
        SysInfoStaticElement StaticInfo { get; };
        SysInfoRealtimeElement RealtimeInfo { get; };
    }
}
