namespace UFCase
{
    [bindable]
    [default_interface]
    runtimeclass SysInfoStaticViewModel
    {
        SysInfoStaticViewModel(UFCase.Isolation.ImageModel model);
        
        // machine-specific online info
        static String FirmwareType();
        static String Manufacturer();
        static String CPUArchitecture();
        static String CPUDisplayName();

        // image-specific OS info
        String OSVersion{ get; };
        String OSArchitecture{ get; };
        String IsWinPE{ get; };
    }
}
