import "SysInfoStaticProvider.idl";
import "SysInfoRealtimeProvider.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass SysInfoPage : Microsoft.UI.Xaml.Controls.Page
    {
        SysInfoPage();
        
        SysInfoStaticProvider StaticInfo { get; };
        SysInfoRealtimeProvider RealtimeInfo { get; };
    }
}
