namespace UFCase
{
    [bindable]
    [default_interface]
    runtimeclass SysInfoStaticElement 
    {
        SysInfoStaticElement();
        // Basic Env
        String FirmwareType;
        String Architecture;

        // OS
        String OSDisplayName;
        String OSVersion;
        Boolean IsWinPE;

        // Firmware
        String Manufacturer;
        String CPUDisplayName;
    }


    [bindable]
    [default_interface]
    runtimeclass SysInfoRealtimeElement : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        SysInfoRealtimeElement();

        Microsoft.UI.Xaml.DispatcherTimer Timer { get; };
        
        Double CPUUtilization { get; };
        String CPUUtilizationComment { get; };

        Double MemoryUsage { get; };
        String MemoryUsageComment { get; };
    }
}
