import "SysInfoStaticViewModel.idl";
import "SysInfoRealtimeProvider.idl";

namespace UFCase
{
    [default_interface]
    runtimeclass SysInfoPage : Microsoft.UI.Xaml.Controls.Page
    {
        SysInfoPage();
        
        SysInfoStaticViewModel StaticInfo { get; };
        SysInfoRealtimeProvider RealtimeInfo { get; };
    }
}
